FROM index.alauda.cn/library/java:7-jre
COPY . /usr/local/rocketmq

ENV rocket.ip “dynamic”
ENV rocket.port “dynamic”
ENV rocket.ha.ip “dynamic”
ENV rocket.ha.port “dynamic”

EXPOSE 10911 10912
WORKDIR /usr/local/rocketmq
ENTRYPOINT ["sh", "mqbroker"]
CMD ["-c", "conf/2m-noslave/broker-a.properties"]