FROM index.alauda.cn/library/java:7-jre
ENV JAVA_HOME /usr/lib/jvm/java-7-openjdk-amd64
WORKDIR /usr/local/rocketmq

ENV rocketmq_ip dynamic
ENV rocketmq_port dynamic
ENV rocketmq_ha_ip dynamic
ENV rocketmq_ha_port dynamic

EXPOSE 10911 10912
COPY . /usr/local/rocketmq
ENTRYPOINT ["sh", "/usr/local/rocketmq/bin/mqbroker"]
CMD ["-c", "conf/2m-noslave/broker-dynamic.properties"]